// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvsqmmfmfhrpdodzltjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2c3FtbWZtZmhycGRvZHpsdGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODg2MzQsImV4cCI6MjA2NDk2NDYzNH0.S7l636TFCZICSBSr-sq-Pc2PbbYiEXb66mZFSkP1WrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);